# NeoStats Retail Data Engineering Pipeline

## End-to-End Workflow

Excel Source Files
↓
Data Ingestion
(Retail Dataset 1, Retail Dataset 2, Product Dimension Table)

↓
Data Quality Checks
- Schema validation
- Missing value detection
- Duplicate record checks

↓
Data Cleaning & Transformation
- Missing price handling
- Invalid record removal
- Category standardization
- Product name standardization
- PII masking

↓
Curated Dataset Creation
- Product dimension merge
- Revenue KPI calculation

↓
Aggregation-Ready Analytics Layer
- Total Revenue
- Revenue by Category
- Revenue by City
- Additional KPIs

↓
Final Dataset Validation

↓
Export Curated Dataset
(cleaned_retail_dataset.csv)

↓
Power BI Dashboard Source

In [134]:
# Import pandas library for data handling and analysis
import pandas as pd

# Import os library for file path operations
import os

# Verify notebook environment is working
print("NeoStats VS Code Ready")

NeoStats VS Code Ready

In [135]:
# Define Excel file location

file = r"G:\Haveloc\USECASE  neostats - Data Engineering.xlsx"

# Display file path to verify
print(file)

G:\Haveloc\USECASE  neostats - Data Engineering.xlsx

In [136]:
# Load Retail Dataset 1
# header=2 means row 3 contains column names

retail1 = pd.read_excel(
    file,
    sheet_name='RETAIL DATA 1',
    header=2
)
# Load Retail Dataset 2
# header=4 means row 5 contains column names

retail2 = pd.read_excel(
    file,
    sheet_name='RETAIL DATA 2',
    header=4
)

In [137]:
# Display first 5 rows of Retail Dataset 1

display(retail1.head())

# Display first 5 rows of Retail Dataset 2

display(retail2.head())

,transaction_id,customer_id,customer_name,product_id,price,product_name,category,purchase_location,city,transaction_date,quantity,payment_method,discount,email,phone,payment_status
0,1,642,Troy Mitchell,108,15000.0,Mixer grinder,Home Appliances,offline,Bangalore,2025-12-06 00:00:00,3,UPI,0.10,Troy60@gmail.com,8385276968,successful
1,2,881,Sarah Guerrero,102,70000.0,Phone,ELEC,online,Bangalore,2025-07-21 00:00:00,5,Card,0.35,SarahGuerrero@yahoo.com,7147248911,successful
2,3,505,Samantha Hull,109,65000.0,Refrigerator,Home Appliances,offline,Chennai,2025-07-11 00:00:00,2,UPI,0.05,SamanthaHull@outlook.com,7415321565,successful
3,4,794,Gerald Cooper,106,80000.0,sofa,FURN,offline,Chennai,2025-10-06 00:00:00,2,UPI,0.05,GeraldCooper@gmail.com,9739354201,successful
4,5,864,Cameron Black,108,15000.0,Mixer grinder,home appliances,offline,Chennai,2025-12-12 00:00:00,1,Cash,0.05,CameronBlack@yahoo.com,9938169477,successful

,transaction_id,customer_id,customer_name,product_id,price,product_name,category,purchase_location,city,transaction_date,quantity,payment_method,discount,email,phone,payment_status
0,4001,1112,Jasmine Carlson,106,80000.0,sofa,Furniture,offline,Delhi,12-18-2025,2,Cash,0.10,JasmineCarlson@gmail.com,8286662057,successful
1,4002,1125,Jeanne Suarez,105,45000.0,Tv,Electronics,online,Mumbai,2025-08-07 00:00:00,3,Card,0.10,JeanneSuarez@yahoo.com,6435924212,successful
2,4003,1379,Anthony Howard,107,50000.0,Dining table,FURN,offline,Delhi,09-19-2025,2,Cash,0.30,Anthony42@gmail.com,8187928333,successful
3,4004,1570,John Wilkins,107,50000.0,DINING TABLE,FURN,offline,Delhi,2025-11-20 00:00:00,2,Cash,0.40,JohnWilkins@outlook.com,6440039629,successful
4,4005,1433,Joseph Knapp,108,15000.0,Mixer grinder,home appliances,online,Bangalore,2025-09-29 00:00:00,5,Cash,0.25,JosephKnapp@gmail.com,9284221237,successful

In [138]:
# Load standardized product dimension table
# header=2 means row 3 contains column names

product = pd.read_excel(
    file,
    sheet_name='PRODUCT DETAILS',
    header=3
)

# Display first few rows

display(product.head())

# Verify product columns

print(product.columns)

   product_id product_name     category   price
0         101       Laptop  Electronics  250000
1         102        Phone  Electronics   70000
2         103        Shirt     Clothing    1300
3         104        Shoes     Clothing    8000
4         105           TV  Electronics   45000

Index(['product_id', 'product_name', 'category', 'price'], dtype='object')

In [139]:
# Check column names for all datasets

print("Retail1 Columns")
print(retail1.columns)

print("\nRetail2 Columns")
print(retail2.columns)

print("\nProduct Columns")
print(product.columns)

Retail1 Columns
Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status'],
      dtype='object')

Retail2 Columns
Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status'],
      dtype='object')

Product Columns
Index(['product_id', 'product_name', 'category', 'price'], dtype='object')

In [140]:
# Combine both retail transaction datasets

retail = pd.concat(
    [retail1, retail2],
    ignore_index=True
)

# Display dataset dimensions
print("Combined Dataset Shape:")
print(retail.shape)

Combined Dataset Shape:
(8494, 16)

In [141]:
# Display first 5 rows of combined dataset

display(
    retail.head()
)

,transaction_id,customer_id,customer_name,product_id,price,product_name,category,purchase_location,city,transaction_date,quantity,payment_method,discount,email,phone,payment_status
0,1,642,Troy Mitchell,108,15000.0,Mixer grinder,Home Appliances,offline,Bangalore,2025-12-06 00:00:00,3,UPI,0.10,Troy60@gmail.com,8385276968,successful
1,2,881,Sarah Guerrero,102,70000.0,Phone,ELEC,online,Bangalore,2025-07-21 00:00:00,5,Card,0.35,SarahGuerrero@yahoo.com,7147248911,successful
2,3,505,Samantha Hull,109,65000.0,Refrigerator,Home Appliances,offline,Chennai,2025-07-11 00:00:00,2,UPI,0.05,SamanthaHull@outlook.com,7415321565,successful
3,4,794,Gerald Cooper,106,80000.0,sofa,FURN,offline,Chennai,2025-10-06 00:00:00,2,UPI,0.05,GeraldCooper@gmail.com,9739354201,successful
4,5,864,Cameron Black,108,15000.0,Mixer grinder,home appliances,offline,Chennai,2025-12-12 00:00:00,1,Cash,0.05,CameronBlack@yahoo.com,9938169477,successful

In [142]:
# Display dataset structure

retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     8494 non-null   int64
 1   customer_id        8494 non-null   int64
 2   customer_name      8494 non-null   object
 3   product_id         8494 non-null   int64
 4   price              7685 non-null   float64
 5   product_name       8494 non-null   object
 6   category           8494 non-null   object
 7   purchase_location  8494 non-null   object
 8   city               8494 non-null   object
 9   transaction_date   8494 non-null   object
 10  quantity           8494 non-null   int64
 11  payment_method     8494 non-null   object
 12  discount           8494 non-null   float64
 13  email              8494 non-null   object
 14  phone              8494 non-null   int64
 15  payment_status     8494 non-null   object
dtypes: float64(2), int64(5), object(9)
memory usage: 1.0+ MB

In [143]:
# Check missing values in every column

missing_values = retail.isnull().sum()

# Display missing value count

print(missing_values)

transaction_id         0
customer_id            0
customer_name          0
product_id             0
price                809
product_name           0
category               0
purchase_location      0
city                   0
transaction_date       0
quantity               0
payment_method         0
discount               0
email                  0
phone                  0
payment_status         0
dtype: int64

In [144]:
# Count duplicate rows

duplicates = retail.duplicated().sum()

# Display duplicate count

print(
    "Duplicate Records:",
    duplicates
)

Duplicate Records: 0

In [145]:
# Display column names

print(
    retail.columns
)

Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status'],
      dtype='object')

In [146]:
# Display column names from both retail datasets

print("Retail1 Columns:")
print(retail1.columns)

print("\nRetail2 Columns:")
print(retail2.columns)

Retail1 Columns:
Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status'],
      dtype='object')

Retail2 Columns:
Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status'],
      dtype='object')

In [147]:
# Fill missing prices using average price of the same product

retail['price'] = retail.groupby(
    'product_id'
)['price'].transform(
    lambda x: x.fillna(
        x.mean()
    )
)

# Verify missing values after cleaning

print(
    retail.isnull().sum()
)

transaction_id       0
customer_id          0
customer_name        0
product_id           0
price                0
product_name         0
category             0
purchase_location    0
city                 0
transaction_date     0
quantity             0
payment_method       0
discount             0
email                0
phone                0
payment_status       0
dtype: int64

In [148]:
print(
    "Negative Prices:",
    (retail['price'] < 0).sum()
)

print(
    "Invalid Quantity:",
    (retail['quantity'] <= 0).sum()
)

Negative Prices: 0
Invalid Quantity: 93

In [149]:
# Remove invalid records

retail = retail[
    (retail['price'] >= 0)
    &
    (retail['quantity'] > 0)
]

# Verify cleaned dataset size

print(
    "Cleaned Dataset Shape:",
    retail.shape
)

Cleaned Dataset Shape: (8401, 16)

In [150]:
# Recheck invalid records after cleaning

print(
    "Negative Prices:",
    (retail['price'] < 0).sum()
)

print(
    "Invalid Quantity:",
    (retail['quantity'] <= 0).sum()
)

Negative Prices: 0
Invalid Quantity: 0

In [151]:
# Standardize category values
# Replace inconsistent category labels

retail['category'] = retail[
    'category'
].replace({

    'ELEC':'Electronics',

    'electronics':'Electronics',

    'FURN':'Furniture',

    'furniture':'Furniture',

    'home appliances':'Home Appliances',

    'HOME':'Home Appliances',

    'CLOTH':'Clothing',

    'clothing':'Clothing'

})

# Verify cleaned categories

print(
    retail['category'].unique()
)

['Home Appliances' 'Electronics' 'Furniture' 'Clothing']

In [152]:
# Standardize product names
# Convert inconsistent capitalization into consistent format

retail['product_name'] = retail[
    'product_name'
].str.title()

# Verify cleaned product names

print(
    retail['product_name'].unique()
)

['Mixer Grinder' 'Phone' 'Refrigerator' 'Sofa' 'Laptop' 'Microwave'
 'Shoes' 'Shirt' 'Tv' 'Dining Table']

In [153]:
# Merge retail dataset with product dimension table
# Join using product_id

curated_dataset = retail.merge(

    product,

    on='product_id',

    how='left',

    suffixes=(
        '_retail',
        '_product'
    )

)

# Preview merged dataset

display(
    curated_dataset.head()
)

,transaction_id,customer_id,customer_name,product_id,price_retail,product_name_retail,category_retail,purchase_location,city,transaction_date,quantity,payment_method,discount,email,phone,payment_status,product_name_product,category_product,price_product
0,1,642,Troy Mitchell,108,15000.0,Mixer Grinder,Home Appliances,offline,Bangalore,2025-12-06 00:00:00,3,UPI,0.10,Troy60@gmail.com,8385276968,successful,Mixer Grinder,Home Appliances,15000
1,2,881,Sarah Guerrero,102,70000.0,Phone,Electronics,online,Bangalore,2025-07-21 00:00:00,5,Card,0.35,SarahGuerrero@yahoo.com,7147248911,successful,Phone,Electronics,70000
2,3,505,Samantha Hull,109,65000.0,Refrigerator,Home Appliances,offline,Chennai,2025-07-11 00:00:00,2,UPI,0.05,SamanthaHull@outlook.com,7415321565,successful,Refrigerator,Home Appliances,65000
3,4,794,Gerald Cooper,106,80000.0,Sofa,Furniture,offline,Chennai,2025-10-06 00:00:00,2,UPI,0.05,GeraldCooper@gmail.com,9739354201,successful,Sofa,Furniture,80000
4,5,864,Cameron Black,108,15000.0,Mixer Grinder,Home Appliances,offline,Chennai,2025-12-12 00:00:00,1,Cash,0.05,CameronBlack@yahoo.com,9938169477,successful,Mixer Grinder,Home Appliances,15000

In [154]:
# Calculate revenue KPI
# Revenue = Price × Quantity × (1 − Discount)

curated_dataset['revenue'] = (

    curated_dataset['price_retail']

    *

    curated_dataset['quantity']

    *

    (
        1 -
        curated_dataset['discount']
    )

)

# Preview revenue calculation

display(

    curated_dataset[
        [
            'product_name_retail',
            'price_retail',
            'quantity',
            'discount',
            'revenue'
        ]
    ].head()

)

  product_name_retail  price_retail  quantity  discount   revenue
0       Mixer Grinder       15000.0         3      0.10   40500.0
1               Phone       70000.0         5      0.35  227500.0
2        Refrigerator       65000.0         2      0.05  123500.0
3                Sofa       80000.0         2      0.05  152000.0
4       Mixer Grinder       15000.0         1      0.05   14250.0

In [155]:
# Display final curated dataset structure

curated_dataset.info()

# Check missing values in final dataset

print(
    curated_dataset.isnull().sum()
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8401 entries, 0 to 8400
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        8401 non-null   int64
 1   customer_id           8401 non-null   int64
 2   customer_name         8401 non-null   object
 3   product_id            8401 non-null   int64
 4   price_retail          8401 non-null   float64
 5   product_name_retail   8401 non-null   object
 6   category_retail       8401 non-null   object
 7   purchase_location     8401 non-null   object
 8   city                  8401 non-null   object
 9   transaction_date      8401 non-null   object
 10  quantity              8401 non-null   int64
 11  payment_method        8401 non-null   object
 12  discount              8401 non-null   float64
 13  email                 8401 non-null   object
 14  phone                 8401 non-null   int64
 15  payment_status        8401 non-null   object
 16  product_name_product  8401 non-null   object
 17  category_product      8401 non-null   object
 18  price_product         8401 non-null   int64
 19  revenue               8401 non-null   float64
dtypes: float64(3), int64(6), object(11)
memory usage: 1.3+ MB
transaction_id          0
customer_id             0
customer_name           0
product_id              0
price_retail            0
product_name_retail     0
category_retail         0
purchase_location       0
city                    0
transaction_date        0
quantity                0
payment_method          0
discount                0
email                   0
phone                   0
payment_status          0
product_name_product    0
category_product        0
price_product           0
revenue                 0
dtype: int64

In [156]:
# Export curated dataset for Power BI

curated_dataset.to_csv(

    r"G:\Haveloc\cleaned_retail_dataset.csv",

    index=False

)

print(
    "Curated dataset exported successfully."
)

Curated dataset exported successfully.

In [157]:
# Mask customer email addresses
# Example:
# Troy60@gmail.com → T***@gmail.com

curated_dataset['email'] = curated_dataset[
    'email'
].str.replace(

    r'(^.).*(@.*$)',

    r'\1***\2',

    regex=True

)

# Verify masked emails

display(

    curated_dataset[
        ['email']
    ].head()

)

              email
0    T***@gmail.com
1    S***@yahoo.com
2  S***@outlook.com
3    G***@gmail.com
4    C***@yahoo.com

In [158]:
# Mask phone numbers
# Example:
# 8385276968 → ******6968

curated_dataset['phone'] = curated_dataset[
    'phone'
].astype(str).str.replace(

    r'\d(?=\d{4})',

    '*',

    regex=True

)

# Verify masked phone numbers

display(

    curated_dataset[
        ['phone']
    ].head()

)

        phone
0  ******6968
1  ******8911
2  ******1565
3  ******4201
4  ******9477

In [159]:
# Export final privacy-protected dataset

curated_dataset.to_csv(

    r"G:\Haveloc\cleaned_retail_dataset.csv",

    index=False

)

print(
    "PII-masked curated dataset exported successfully."
)

PII-masked curated dataset exported successfully.

In [160]:
# Calculate Total Revenue KPI

total_revenue = curated_dataset[
    'revenue'
].sum()

# Display KPI

print(
    "Total Revenue:",
    total_revenue
)

Total Revenue: 1239132235.0

In [161]:
# Calculate Revenue by Category

revenue_by_category = curated_dataset.groupby(

    'category_retail'

)[
    'revenue'
].sum().sort_values(
    ascending=False
)

# Display result

print(
    revenue_by_category
)

category_retail
Electronics        721682500.0
Furniture          257064000.0
Home Appliances    242328000.0
Clothing            18057735.0
Name: revenue, dtype: float64

In [162]:
# Calculate Revenue by City

revenue_by_city = curated_dataset.groupby(

    'city'

)[
    'revenue'
].sum().sort_values(
    ascending=False
)

# Display result

print(
    revenue_by_city
)

city
Chennai      259249060.0
Delhi        256872880.0
Hyderabad    248807740.0
Mumbai       247071395.0
Bangalore    227131160.0
Name: revenue, dtype: float64

In [163]:
# Calculate total transaction count

total_orders = curated_dataset[
    'transaction_id'
].nunique()

print(
    "Total Orders:",
    total_orders
)

Total Orders: 7914

In [164]:
# Calculate average revenue per transaction

average_revenue = curated_dataset[
    'revenue'
].mean()

print(
    "Average Revenue:",
    average_revenue
)

Average Revenue: 147498.18295441018

In [165]:
# Revenue by payment method

revenue_by_payment = curated_dataset.groupby(

    'payment_method'

)[
    'revenue'
].sum().sort_values(
    ascending=False
)

print(
    revenue_by_payment
)

payment_method
Card          324934475.0
Cash          318279145.0
UPI           307074335.0
NetBanking    288844280.0
Name: revenue, dtype: float64

In [166]:
# Final curated dataset validation

print(
    curated_dataset.shape
)

print(
    curated_dataset.isnull().sum()
)

display(
    curated_dataset.head()
)

(8401, 20)
transaction_id          0
customer_id             0
customer_name           0
product_id              0
price_retail            0
product_name_retail     0
category_retail         0
purchase_location       0
city                    0
transaction_date        0
quantity                0
payment_method          0
discount                0
email                   0
phone                   0
payment_status          0
product_name_product    0
category_product        0
price_product           0
revenue                 0
dtype: int64

,transaction_id,customer_id,customer_name,product_id,price_retail,product_name_retail,category_retail,purchase_location,city,transaction_date,quantity,payment_method,discount,email,phone,payment_status,product_name_product,category_product,price_product,revenue
0,1,642,Troy Mitchell,108,15000.0,Mixer Grinder,Home Appliances,offline,Bangalore,2025-12-06 00:00:00,3,UPI,0.10,T***@gmail.com,******6968,successful,Mixer Grinder,Home Appliances,15000,40500.0
1,2,881,Sarah Guerrero,102,70000.0,Phone,Electronics,online,Bangalore,2025-07-21 00:00:00,5,Card,0.35,S***@yahoo.com,******8911,successful,Phone,Electronics,70000,227500.0
2,3,505,Samantha Hull,109,65000.0,Refrigerator,Home Appliances,offline,Chennai,2025-07-11 00:00:00,2,UPI,0.05,S***@outlook.com,******1565,successful,Refrigerator,Home Appliances,65000,123500.0
3,4,794,Gerald Cooper,106,80000.0,Sofa,Furniture,offline,Chennai,2025-10-06 00:00:00,2,UPI,0.05,G***@gmail.com,******4201,successful,Sofa,Furniture,80000,152000.0
4,5,864,Cameron Black,108,15000.0,Mixer Grinder,Home Appliances,offline,Chennai,2025-12-12 00:00:00,1,Cash,0.05,C***@yahoo.com,******9477,successful,Mixer Grinder,Home Appliances,15000,14250.0

In [167]:
# Export final curated dataset

curated_dataset.to_csv(

    r"G:\Haveloc\cleaned_retail_dataset.csv",

    index=False

)

print(
    "Final curated dataset exported successfully."
)

Final curated dataset exported successfully.